routes/backend.php
<?php

//use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
|
|
|
*/

Route::get('/', function () {
  return redirect()->route('backend.profile.index');
});

//Auth::routes();
Route::name('backend.auth.')
  ->namespace('Backend\Auth')
  ->group(function(){
    Route::get('/login', 'LoginController@showLoginForm')->name('login.form');
    Route::post('/login', 'LoginController@login')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});


//Backend group
Route::name('backend.')
  ->namespace('Backend')
/*  ->prefix('/backend')*/
  ->middleware(['backend.auth', 'user.active'])
  ->group(function(){
    // Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('/home', function(){
      // return redirect()->route('backend.dashboard');
      return redirect()->route("backend.profile.index");
    });

    // Trash
    Route::name('trash.')
      ->prefix('/trash')
      ->group(function(){
        Route::get('/', 'TrashController@index')->name('index');
        Route::get('/{model}/restore-all', 'TrashController@restoreAll')->name('restore-all');
        Route::get('/{model}/remove-all', 'TrashController@removeAll')->name('remove-all');
        Route::get('/{model}/{modelId}/restore', 'TrashController@restore')->name('restore');
        Route::get('/{model}/{modelId}/remove', 'TrashController@remove')->name('remove');
      });

    //Role
    Route::name('role.')
      ->prefix('/role')
      ->group(function(){
        Route::get('/search', 'RoleController@search')->name('search');
     
    });
    Route::resource('/role', 'RoleController');

    //User
    Route::name('user.')
      ->prefix('/user')
      ->group(function(){
        Route::get('/search', 'UserController@search')->name('search');
    
    });  
    Route::resource('/user', 'UserController');

    Route::resource('/profile', 'ProfileController');

    Route::resource('/webinfo', 'WebInfoController');

    Route::resource('/about', 'AboutUsController');

    Route::name('websocial.')
      ->prefix('/websocial')
      ->group(function(){
        Route::get('/search', 'WebSocialController@search')->name('search');
    });
    Route::resource('/websocial', 'WebSocialController');
  
    Route::name('page.')
      ->prefix('/page')
      ->group(function(){
        Route::get('/search', 'PageController@search')->name('search');
    });
    Route::resource('/page', 'PageController');

     Route::name('banner.')
      ->prefix('/banner')
      ->group(function(){
        Route::get('/search', 'BannerController@search')->name('search');
    });
    Route::resource('/banner', 'BannerController');

    Route::name('menu.')
      ->prefix('/menu')
      ->group(function(){
        Route::get('/search', 'MenuController@search')->name('search');
        Route::post('/change_position', 'MenuController@change_position')->name('change_position');
        Route::get('/edit_name', 'MenuController@edit_name')->name('edit_name');
        Route::post('/update_name', 'MenuController@update_name')->name('update_name');
    });
    Route::resource('/menu', 'MenuController');

    Route::name('food_type.')
      ->prefix('/food_type')
      ->group(function(){
        Route::get('/search', 'FoodTypeController@search')->name('search');
    });
    Route::resource('/food_type', 'FoodTypeController');

    Route::name('buffet_type.')
      ->prefix('/buffet_type')
      ->group(function(){
        Route::get('/search', 'BuffetTypeController@search')->name('search');
    });
    Route::resource('/buffet_type', 'BuffetTypeController');

    Route::name('menu_buffet.')
      ->prefix('/menu_buffet')
      ->group(function(){
        Route::get('/search', 'MenuBuffetController@search')->name('search');
    });
    Route::resource('/menu_buffet', 'MenuBuffetController');

    Route::resource('/alacarte', 'AlacarteController');

    Route::name('menu_alacarte.')
      ->prefix('/menu_alacarte')
      ->group(function(){
        Route::get('/search', 'MenuAlacarteController@search')->name('search');
    });
    Route::resource('/menu_alacarte', 'MenuAlacarteController');

    Route::name('menu_delivery.')
      ->prefix('/menu_delivery')
      ->group(function(){
        Route::get('/search', 'MenuDeliveryController@search')->name('search');
    });
    Route::resource('/menu_delivery', 'MenuDeliveryController');

    Route::name('promotion.')
      ->prefix('/promotion')
      ->group(function(){
        Route::get('/search', 'PromotionController@search')->name('search');
    });
    Route::resource('/promotion', 'PromotionController');
 
    Route::name('branch.')
      ->prefix('/branch')
      ->group(function(){
        Route::get('/search', 'BranchController@search')->name('search');
    });
    Route::resource('/branch', 'BranchController');

    Route::name('review.')
      ->prefix('/review')
      ->group(function(){
        Route::get('/search', 'ReviewController@search')->name('search');
    });
    Route::resource('/review', 'ReviewController');

    Route::name('delivery.')
      ->prefix('/delivery')
      ->group(function(){
        Route::get('/search', 'DeliveryController@search')->name('search');
    });
    Route::resource('/delivery', 'DeliveryController');

    Route::name('contact.')
      ->prefix('/contact')
      ->group(function(){
        Route::get('/search', 'ContactUsController@search')->name('search');
    });
    Route::resource('/contact', 'ContactUsController');

    Route::resource('/gallery', 'GalleryController');

    //ck editor
    Route::name('ckeditor.')
      ->prefix('/ckeditor')
      ->group(function(){
        Route::post('/upload', 'CkeditorController@upload')->name('upload');
    }); 
    Route::get('ckeditor', 'CkeditorController@index');

    Route::name('dropzone.')
      ->prefix('/dropzone')
      ->group(function(){
        Route::post('/upload', 'DropzoneController@upload')->name('upload');
    }); 



});

routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Cache;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
  return redirect(route('frontend.home', ['locale' => app()->getLocale()]));
});

Route::name('frontend.')
  ->namespace('Frontend')
  ->prefix('{locale}') 
  ->where(['locale' => '[a-zA-Z]{2}']) 
  ->middleware('setlocale')
  ->group(function(){

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/about', 'AboutController@index')->name('about');
    Route::get('/promotion', 'PromotionController@index')->name('promotion');
    Route::get('/promotion/{promotion}', 'PromotionController@detail')->name('promotion-detail');
    Route::get('/review', 'ReviewController@index')->name('review');
    Route::get('/review/{review}', 'ReviewController@detail')->name('review-detail');
    Route::get('/gallery', 'GalleryController@index')->name('gallery');
    Route::get('/branch', 'BranchController@index')->name('branch');
    Route::get('/contactus', 'ContactUsController@index')->name('contact');
    Route::get('/menu_alacarte', 'AlacarteMenuController@index')->name('alacarte_menu');
    Route::get('/menu_buffet', 'BuffetMenuController@index')->name('buffet_menu');
    Route::get('/menu_delivery', 'DeliveryMenuController@index')->name('delivery_menu');

    Route::resource('/contact', 'ContactUsController');

    Route::get('/lang', function () {
      return back()->withInput(['locale' => app()->getLocale()]);
      //return redirect(route('frontend.home', ['locale' => app()->getLocale()]));
    });

    /* Sitemap Route*/
    Route::get('/sitemap.xml', 'SitemapController@index')->name('sitemap.xml');
    Route::get('/sitemap.xml/reviews', 'SitemapController@reviews');
});

Route::name('frontend.')
->namespace('Frontend')
  ->group(function(){

    set_time_limit(0);
    
    Route::get('/clearCache', function () {
      Cache::flush();
      $exitCode = Artisan::call('config:cache');
      return 'Cache Clear';
    });

    Route::get('/clearConfig', function () {
      $exitCode = Artisan::call('config:clear');
      return 'Config Clear';
    });

    Route::get('/createKey', function () {
      Artisan::call('key:generate');
      return 'Success';
    });

    Route::get('/createLink', function () {
      Artisan::call('storage:link');
      return 'Success';
    });

    Route::get('/migrate', function () {
      Artisan::call('migrate:fresh --seed');
      return 'Success';
    });

});


Auth::routes();

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Model\AboutUs;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AboutUsController extends Controller
{
  const MODULE = 'about';

  public function index()
  {
    $this->authorize(mapPermission(self::MODULE));
    $about = AboutUs::find(1)->first();

    return view('backend.about_us.update', compact('about'));
  }

  public function update(Request $request, AboutUs $about)
  {
    $this->authorize(mapPermission(self::MODULE));
    $about->update($this->validateRequest());
    $about->storeImage();

    return redirect(route('backend.about.index'));
  }

  private function validateRequest() {
    $validatedData = request()->validate([
      "title_th"               => "required",
      "title_en"               => "required",
      "title_cn"               => "required",
      "description1_th"        => "required",
      "description1_en"        => "required",
      "description1_cn"        => "required",
      "description2_th"        => "required",
      "description2_en"        => "required",
      "description2_cn"        => "required",
      "description3_th"        => "required",
      "description3_en"        => "required",
      "description3_cn"        => "required",
    ]);

    $validatedData['updated_by'] = Auth::id();
    $validateImg = request()->validate([
      "image1"       => ['sometimes', 'file','image','max:5000'],
      "image2"       => ['sometimes', 'file','image','max:5000'],
      "image3"       => ['sometimes', 'file','image','max:5000'],
    ]);

    return $validatedData;
  }

}

app/Http/Controllers/Backend/AlacarteController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Alacarte;
use Illuminate\Support\Facades\Auth;

class AlacarteController extends Controller
{
  const MODULE = 'menu_alacarte';

  public function index(Request $request) 
  {
    $this->authorize(mapPermission(self::MODULE));
    $alacarte = Alacarte::find(1)->first();

    return view('backend.alacarte.update', compact('alacarte'));
  }

  public function update(Request $request, Alacarte $alacarte) {
    $this->authorize(mapPermission(self::MODULE));
    $alacarte->update($this->validateRequest());

    return redirect(route('backend.alacarte.index'));
  }

  public function destroy(Alacarte $alacarte) {
    $this->authorize(mapPermission(self::MODULE));
    $alacarte->delete();

    return redirect(route('backend.alacarte.index'));
  }

  private function validateRequest() {
    $validatedData = request()->validate([
      "detail_th"   => "required",
      "detail_en"   => "required",
      "detail_cn"   => "required",
      "active" => "",
    ]);

    request()->validate([
      "image"  => ['sometimes', 'file','image','max:1000'],
    ]);

    $validatedData['updated_by'] = Auth::id();
    if(request()->route()->getActionMethod() == 'store') :
      $validatedData['created_by'] = Auth::id();
    endif;

    return $validatedData;
  }

}

app/Http/Controllers/Backend/BranchController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Branch;
use Illuminate\Support\Facades\Auth;

class BranchController extends Controller
{
  const MODULE = 'branch';

  public function index(Request $request) 
  {
    $this->authorize(mapPermission(self::MODULE));
    if ($request->filled('keyword')):
      $branchs = Branch::getDataByKeyword($request->keyword)->get();
    else:
      $branchs = Branch::limit(50)->get();
    endif;

    return view('backend.branch.index', compact('branchs'));
  }

  public function search(Request $request) {
    $this->authorize(mapPermission(self::MODULE));
    if ($request->filled('keyword')):
      $branchs = Branch::getDataByKeyword($request->keyword)->get();
    else:
      $branchs = Branch::all();
    endif;

    return view('backend.branch.show', compact('branchs'));
  }

  public function create() {
    $this->authorize(mapPermission(self::MODULE));
    $branch = new Branch;

    return view('backend.branch.create', compact('branch'));

  }

  public function store(Request $request) {
    $this->authorize(mapPermission(self::MODULE));
    $branch = Branch::create($this->validateRequest());
    $branch->storeImage();

    return redirect(route('backend.branch.index'));
  }

  public function edit(Branch $branch) {
    $this->authorize(mapPermission(self::MODULE));

    return view('backend.branch.update', compact('branch'));
  }

  public function update(Request $request, Branch $branch) {
    $this->authorize(mapPermission(self::MODULE));
    $branch->update($this->validateRequest());
    $branch->storeImage();

    return redirect(route('backend.branch.index'));
  }

  public function destroy(Branch $branch) {
    $this->authorize(mapPermission(self::MODULE));
    $branch->delete();

    return redirect(route('backend.branch.index'));
  }

  private function validateRequest() {
    $validatedData = request()->validate([
      "name_th"   => "required",
      "name_en"   => "required",
      "name_cn"   => "required",
      "address_th"   => "required",
      "address_en"   => "required",
      "address_cn"   => "required",
      "telephone"    => "required",
      "line"    => "required",
      "office_hours"    => "required",
      "description_th" => "",
      "description_en" => "",
      "description_cn" => "",
      "active" => "",
    ]);

    request()->validate([
      "image"  => ['sometimes', 'file','image','max:5000'],
    ]);

    $validatedData['updated_by'] = Auth::id();
    if(request()->route()->getActionMethod() == 'store') :
      $validatedData['created_by'] = Auth::id();
    endif;

    return $validatedData;
  }

}

app/Http/Controllers/Backend/BuffetTypeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\BuffetType;
use Illuminate\Support\Facades\Auth;

class BuffetTypeController extends Controller
{
  const MODULE = 'buffet_type';

  public function index(Request $request) 
  {
    $this->authorize(mapPermission(self::MODULE));
    if ($request->filled('keyword')):
      $buffet_types = BuffetType::getDataByKeyword($request->keyword)->get();
    else:
      $buffet_types = BuffetType::limit(50)->get();
    endif;

    return view('backend.buffet_type.index', compact('buffet_types'));
  }

  public function search(Request $request) {
    $this->authorize(mapPermission(self::MODULE));
    if ($request->filled('keyword')):
      $buffet_types = BuffetType::getDataByKeyword($request->keyword)->get();
    else:
      $buffet_types = BuffetType::all();
    endif;

    return view('backend.buffet_type.show', compact('buffet_types'));
  }

  public function create() {
    $this->authorize(mapPermission(self::MODULE));
    $buffet_type = new BuffetType;

    return view('backend.buffet_type.create', compact('buffet_type'));

  }

  public function store(Request $request) {
    $this->authorize(mapPermission(self::MODULE));
    $buffet_type = BuffetType::create($this->validateRequest());
    $buffet_type->storeImage();

    return redirect(route('backend.buffet_type.index'));
  }

  public function edit(BuffetType $buffet_type) {
    $this->authorize(mapPermission(self::MODULE));

    return view('backend.buffet_type.update', compact('buffet_type'));
  }

  public function update(Request $request, BuffetType $buffet_type) {
    $this->authorize(mapPermission(self::MODULE));
    $buffet_type->update($this->validateRequest());
    $buffet_type->storeImage();

    return redirect(route('backend.buffet_type.index'));
  }

  public function destroy(BuffetType $buffet_type) {
    $this->authorize(mapPermission(self::MODULE));
    $buffet_type->delete();

    return redirect(route('backend.buffet_type.index'));
  }

  private function validateRequest() {
    $validatedData = request()->validate([
      "name_th"   => "required",
      "name_en"   => "required",
      "name_cn"   => "required",
      "description_th" => "",
      "description_en" => "",
      "description_cn" => "",
      "detail_th" => "",
      "detail_en" => "",
      "detail_cn" => "",
      "price"    => "required",
      "active" => "",
    ]);

    request()->validate([
      "image"  => ['sometimes', 'file','image','max:5000'],
    ]);

    $validatedData['updated_by'] = Auth::id();
    if(request()->route()->getActionMethod() == 'store') :
      $validatedData['created_by'] = Auth::id();
    endif;

    return $validatedData;
  }

}

resources/views/backend/page/create.blade.php
@extends('backend.layouts.header')
@section('title')
	เพิ่มหน้า
@endsection
@section('content')

<!-- begin row -->
<div class="row">
  <!-- begin col-6 -->
  <div class="col-lg-12">
    <!-- begin panel -->
    <div class="panel " data-sortable-id="form-validation-1">
      <!-- begin panel-heading -->
      <div class="panel-heading panel-black">
        <h5 class="text-white">ข้อมูลหน้า</h5>
      </div>
      <!-- end panel-heading -->
      <!-- begin panel-body -->
      <div class="panel-body">
        <form class="form-horizontal" method="post"  id="form-validate" name="demo-form" enctype="multipart/form-data" action="{{ route('backend.page.store') }}" >
            @method('post')
            @include('backend.page.form')
            @csrf

          </form>  
        </div>
        <!-- end panel-body -->
      </div>
      <!-- end panel -->
    </div>
    <!-- end col-6 -->
  </div>
  <!-- end row -->

@endsection

resources/views/backend/page/index.blade.php
@extends('backend.layouts.header')
@section('title')
	หน้า
@endsection
@section('content')

	<div class="row">
   	<div class="col-12 col-xl-12">
      <div class="panel panel-inverse gray">
        <div class="panel-body mgbt">
          <form id="" action="{{ route('backend.page.index') }}" method='post' data-parsley-validate="true">
            @method('get')
            @csrf
            <div class="form-row">    
              <div class="form-group col-md-4 col-lg-2">
                <label for="StopDate">คีย์เวิร์ด </label>
                <input type="text" class="form-control " name="keyword" value="{{ request('keyword') ?? '' }}" >
              </div>
              <div class="form-group col-lg-6 col-md-12 col-sm-12 ">
                <div class='mt-4 '>
                  <button type="submit" class="btn btn-white btn-search" id="search"><i class='fas fa-search text-info'></i> ค้นหา </button>
                  {{-- @can('add page')
                    <a href="{{ route('backend.page.create') }}" class="btn btn-white btn-search"><i class="fa fa-plus-square fa-lg text-success"></i> เพิ่มข้อมูล</a>
                  @endcan --}}
                </div>
              </div>   

           	</div>              
         	</form>
       	</div>
      </div>
    </div>
  </div>

  <div class="return-list">
    <!-- begin row -->
    <div class="row">
      <!-- begin col-12 -->
      <div class="col-lg-12">
        <!-- begin panel -->
        <div class="panel ">
          <!-- begin panel-heading -->
         
          <!-- end panel-heading -->
          <!-- begin panel-body -->
          <div class="panel-body">
            <table id="data-table-list" class="table table-striped table-bordered w-100 nowrap ">
              <thead>
                <tr>
                  <!-- <th width="1%">ลำดับ</th> -->
                  <th class="text-center">จัดการ</th>
                  <th class="text-center">วันที่อัพเดต</th>
                  <th class="text-center">ชื่อหน้า</th>
                  <th class="text-center">Title(ไทย)</th>
                  <th class="text-center">Title(อังกฤษ)</th>
                  <th class="text-center">Title(จีน)</th>
                  <th class="text-center">ผู้แก้ไขล่าสุด</th>
                </tr>
              </thead>
              <tbody>
              
                @if(!empty($pages)) 
                  @foreach($pages as $page)
                    <tr class='del'>
                      <td class="text-center">
                        <div class="dropright">
                          <button class="btn btn-white dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           <i class="fas fa-bars "></i>
                             <span class="sr-only">Toggle Dropdown</span>
                          </button>

                          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          @can('delete page')
                            <form action="{{ route('backend.page.destroy', ['page' => $page->id]) }}" method='post' >
                             {{ method_field('DELETE') }}
                               <button class="del-trans  dropdown-item" data-id="" data-module="Del" data-controller="" 
                                ><i class="fa fa-trash text-danger"></i>&nbsp;&nbsp; ลบ </button>
                                 @csrf
                            </form>
                          @endcan
                          @can('edit page')
                            <div class="dropdown-divider"></div>
                            <a href="{{ route('backend.page.edit', ['page' => $page->id]) }}" class=" edit  dropdown-item" data-id="" ><i class="fa fa-pencil-alt text-warning"></i>&nbsp;&nbsp; แก้ไข </a>
                          @endcan

                        </div>
                      </div>
                      </td>

                      <td class="text-center">{{ date('d/m/Y H:i:s', strtotime($page->updated_at)) }}</td>
                      <td class="text-left">{{ $page->name }}</td>
                      <td class="text-left">{{ $page->title_th }}</td>
                      <td class="text-left">{{ $page->title_en }}</td>
                      <td class="text-left">{{ $page->title_cn }}</td>
                      <td class="text-center">{{ $page->update_name->name }}</td>
                    </tr>
                  @endforeach
               	@endif
              </tbody>
            </table>
          </div>
          <!-- end panel-body -->
        </div>
        <!-- end panel -->
      </div>
      <!-- end col-12 -->
    </div>
    <!-- end row -->
  </div>

  <?php  $colum_width = json_encode(
    array([ "width" => "40px", "targets" => 0 ],
          [ "width" => "100px", "targets" => 1 ],
          [ "width" => "150px", "targets" => 2 ],
          [ "width" => "200px", "targets" => 3 ],
          [ "width" => "200px", "targets" => 4 ],
     

        )
  ); ?>

	<script>
	  var colum_width = '<?php echo $colum_width; ?>';
	</script>

@endsection

resources/views/backend/page/show.blade.php
      <!-- begin row -->
      <div class="row">
        <!-- begin col-12 -->
        <div class="col-lg-12">
          <!-- begin panel -->
          <div class="panel ">
            <!-- begin panel-heading -->
           
            <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
              <table id="data-table-list" class="table table-striped table-bordered w-100 nowrap ">
                <thead>
                  <tr>
                    <!-- <th width="1%">ลำดับ</th> -->
                    <th class="text-center">จัดการ</th>
                    <th class="text-center">วันที่อัพเดต</th>
                    <th class="text-center">ชื่อหน้า</th>
                    <th class="text-center">Title(ไทย)</th>
                    <th class="text-center">Title(อังกฤษ)</th>
                    <th class="text-center">Title(จีน)</th>
                    <th class="text-center">ผู้แก้ไขล่าสุด</th>
                  </tr>
                </thead>
                <tbody>
                
                  @if(!empty($pages)) 
                    @foreach($pages as $page)
                      <tr class='del'>
                        <td class="text-center">
                          <div class="dropright">
                            <button class="btn btn-white dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                             <i class="fas fa-bars "></i>
                               <span class="sr-only">Toggle Dropdown</span>
                            </button>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            @can('delete page')
                              <form action="{{ route('backend.page.destroy', ['page' => $page->id]) }}" method='post' >
                               {{ method_field('DELETE') }}
                                 <button class="del-trans  dropdown-item" data-id="" data-module="Del" data-controller="" 
                                  ><i class="fa fa-trash text-danger"></i>&nbsp;&nbsp; ลบ </button>
                                   @csrf
                              </form>
                            @endcan
                            @can('edit page')
                              <div class="dropdown-divider"></div>
                              <a href="{{ route('backend.page.edit', ['page' => $page->id]) }}" class=" edit  dropdown-item" data-id="" ><i class="fa fa-pencil-alt text-warning"></i>&nbsp;&nbsp; แก้ไข </a>
                            @endcan

                          </div>
                        </div>
                        </td>

                        <td class="text-center">{{ date('d/m/Y H:i:s', strtotime($page->updated_at)) }}</td>
                        <td class="text-left">{{ $page->name }}</td>
                        <td class="text-left">{{ $page->title_th }}</td>
                        <td class="text-left">{{ $page->title_en }}</td>
                        <td class="text-left">{{ $page->title_cn }}</td>
                        <td class="text-center">{{ $page->update_name->name }}</td>
                      </tr>
                    @endforeach
                  @endif
                </tbody>
              </table>
            </div>
            <!-- end panel-body -->
          </div>
          <!-- end panel -->
        </div>
        <!-- end col-12 -->
      </div>
      <!-- end row -->

resources/views/backend/page/update.blade.php
@extends('backend.layouts.header')
@section('title')
	แก้ไขหน้า
@endsection
@section('content')

<!-- begin row -->
<div class="row">
  <!-- begin col-6 -->
  <div class="col-lg-12">
    <!-- begin panel -->
    <div class="panel " data-sortable-id="form-validation-1">
      <!-- begin panel-heading -->
      <div class="panel-heading panel-black">
        <h5 class="text-white">ข้อมูลหน้า</h5>
      </div>
      <!-- end panel-heading -->
      <!-- begin panel-body -->
      <div class="panel-body">
        <form class="form-horizontal"  id="form-validate" name="demo-form" enctype="multipart/form-data" action="{{ route('backend.page.update', ['page' => $page->id] ) }}"  method='post'>
            @method('PATCH')
            @include('backend.page.form')
             @csrf
          </form>  
        </div>
        <!-- end panel-body -->
      </div>
      <!-- end panel -->
    </div>
    <!-- end col-6 -->
  </div>
  <!-- end row -->

@endsection